import { parse, type HTMLElement } from 'node-html-parser'
import type { CheckResult } from '../../../shared/types.js'
import type { BuildFacts } from '../../../shared/plan.js'
import { pageWeight } from '../assets.js'
import { formatBytes } from '../images.js'

/**
 * Static verification. Brief s6 checks 1 to 12, plus check 17, page weight.
 *
 * Runs on every generation and every edit, before the customer sees anything. No browser
 * required, which is the point: these run everywhere, including in CI and on a laptop with no
 * headless Chromium, and they are the checks that catch most real faults.
 *
 * Structure comes from a real HTML parser. Text-level rules run over the raw source, because a
 * banned character inside a comment or an attribute still counts.
 *
 * Every failure carries evidence, and the evidence is fed into the repair prompt verbatim, so
 * "found 3 em dashes" is useless and "line 412: ...text..." is not.
 */

export const FOOTER_CREDIT_TEXT = 'Website by Go Polar Creative'
export const FOOTER_CREDIT_HREF = 'https://www.itscold.com.au'
export const FORM_ACTION = 'https://api.web3forms.com/submit'

/** Brief-derived budget. Warn above the first, fail above the second. */
export const PAGE_WEIGHT_TARGET = 2 * 1024 * 1024
export const PAGE_WEIGHT_WARN = 2.5 * 1024 * 1024
export const PAGE_WEIGHT_FAIL = 5 * 1024 * 1024

interface Structure {
  headings: Array<{ level: number; text: string }>
  imgs: Array<{ src: string; alt: string | null }>
  sources: string[]
  forms: Array<{ action: string | null }>
  jsonLd: string[]
  htmlLang: string | null
  footerCredit: { text: string; target: string | null } | null
  linkHrefs: string[]
  scriptSrcs: string[]
  styleAttrs: string[]
  svgColourAttrs: string[]
  /** Every element carrying the mobile-bar block class. Exactly one is correct. */
  mobileBars: Array<{ parent: string; classes: string }>
}

function readStructure(html: string): Structure {
  const root = parse(html, {
    lowerCaseTagName: true,
    comment: false,
    blockTextElements: { script: true, style: true, pre: true },
  })

  const headings = root
    .querySelectorAll('h1, h2, h3, h4, h5, h6')
    .map((el) => ({ level: Number(el.rawTagName.slice(1)), text: el.text.trim().slice(0, 80) }))

  const imgs = root.querySelectorAll('img').map((el) => ({
    src: el.getAttribute('src') ?? '',
    alt: el.getAttribute('alt') ?? null,
  }))

  const sources = root
    .querySelectorAll('source')
    .map((el) => el.getAttribute('srcset') ?? '')
    .filter(Boolean)

  const forms = root.querySelectorAll('form').map((el) => ({ action: el.getAttribute('action') ?? null }))

  const jsonLd = root
    .querySelectorAll('script')
    .filter((el) => (el.getAttribute('type') ?? '').includes('ld+json'))
    .map((el) => el.text)

  const htmlEl: HTMLElement | null = root.querySelector('html')
  const htmlLang = htmlEl?.getAttribute('lang') ?? null

  let footerCredit: Structure['footerCredit'] = null
  for (const el of root.querySelectorAll('a')) {
    const href = el.getAttribute('href')
    if (href === FOOTER_CREDIT_HREF || href === `${FOOTER_CREDIT_HREF}/`) {
      footerCredit = { text: el.text.trim(), target: el.getAttribute('target') ?? null }
      break
    }
  }

  const linkHrefs = root
    .querySelectorAll('link')
    .map((el) => el.getAttribute('href') ?? '')
    .filter(Boolean)

  const scriptSrcs = root
    .querySelectorAll('script')
    .map((el) => el.getAttribute('src') ?? '')
    .filter(Boolean)

  const styleAttrs = root
    .querySelectorAll('[style]')
    .map((el) => el.getAttribute('style') ?? '')
    .filter(Boolean)

  const svgColourAttrs: string[] = []
  for (const attr of ['fill', 'stroke', 'stop-color']) {
    for (const el of root.querySelectorAll(`[${attr}]`)) {
      const value = el.getAttribute(attr)
      if (value) svgColourAttrs.push(`${attr}="${value}"`)
    }
  }

  // The mobile sticky call bar. The footer section prompt is the only one told to emit it, but
  // each section is generated by a separate model call that can only see the house rules, and
  // those describe the bar under the header heading too. When two calls both emit it, the page
  // ends up with one bar high in the document behind the fixed header and one in the right place.
  const mobileBars = root
    .querySelectorAll('[class]')
    .filter((el) => (el.getAttribute('class') ?? '').split(/\s+/).includes('mobile-bar'))
    .map((el) => ({
      parent: el.parentNode?.rawTagName ?? 'body',
      classes: el.getAttribute('class') ?? '',
    }))

  return {
    headings,
    imgs,
    sources,
    forms,
    jsonLd,
    htmlLang,
    footerCredit,
    linkHrefs,
    scriptSrcs,
    styleAttrs,
    svgColourAttrs,
    mobileBars,
  }
}

// ---------------------------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------------------------

const pass = (id: CheckResult['id'], label: string): CheckResult => ({ id, label, status: 'pass' })
const fail = (
  id: CheckResult['id'],
  label: string,
  detail: string,
  evidence: string[] = [],
): CheckResult => ({ id, label, status: 'fail', detail, evidence: evidence.slice(0, 8) })

function lineOf(html: string, index: number): number {
  let line = 1
  for (let i = 0; i < index && i < html.length; i++) if (html[i] === '\n') line++
  return line
}

function context(html: string, index: number, width = 70): string {
  const start = Math.max(0, index - width / 2)
  return html
    .slice(start, start + width)
    .replace(/\s+/g, ' ')
    .trim()
}

/** Byte ranges of every :root { ... } block, so colours inside them are allowed. */
function rootRanges(html: string): Array<[number, number]> {
  const ranges: Array<[number, number]> = []
  const re = /:root\s*\{/g
  let m: RegExpExecArray | null
  while ((m = re.exec(html)) !== null) {
    let depth = 1
    let i = m.index + m[0].length
    while (i < html.length && depth > 0) {
      if (html[i] === '{') depth++
      else if (html[i] === '}') depth--
      i++
    }
    ranges.push([m.index, i])
  }
  return ranges
}

function inRanges(index: number, ranges: Array<[number, number]>): boolean {
  return ranges.some(([a, b]) => index >= a && index < b)
}

const NAMED_COLOURS = [
  'white', 'black', 'red', 'blue', 'green', 'grey', 'gray', 'silver', 'navy', 'orange',
  'yellow', 'purple', 'gold', 'teal', 'pink', 'brown', 'maroon', 'olive', 'lime', 'aqua',
  'fuchsia', 'beige', 'ivory', 'coral', 'crimson', 'indigo', 'khaki', 'salmon', 'tan',
  'violet', 'wheat', 'azure', 'lavender', 'plum', 'orchid', 'tomato', 'turquoise',
]

// ---------------------------------------------------------------------------------------------
// Checks 1 to 12
// ---------------------------------------------------------------------------------------------

function checkHexOutsideRoot(html: string, s: Structure): CheckResult {
  const id = 'hex_outside_root' as const
  const label = 'No colour values outside :root'
  const ranges = rootRanges(html)
  const evidence: string[] = []

  // Scope: CSS only. That is what the rule is about, and the only place a token could have been
  // used instead. <meta name="theme-color" content="#..."> is deliberately NOT a violation: a
  // meta attribute cannot take a var(), so a literal there is the only option.
  const styleBlocks = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)]
  for (const block of styleBlocks) {
    const body = block[1] ?? ''
    const offset = (block.index ?? 0) + block[0].indexOf(body)

    const hexRe = /#[0-9a-fA-F]{3,8}\b/g
    let m: RegExpExecArray | null
    while ((m = hexRe.exec(body)) !== null) {
      const absolute = offset + m.index
      if (inRanges(absolute, ranges)) continue
      if (/url\(\s*['"]?$/.test(body.slice(Math.max(0, m.index - 14), m.index))) continue
      evidence.push(`line ${lineOf(html, absolute)}: ${context(html, absolute)}`)
    }

    const funcRe = /\b(rgba?|hsla?)\s*\(/g
    while ((m = funcRe.exec(body)) !== null) {
      const absolute = offset + m.index
      if (inRanges(absolute, ranges)) continue
      evidence.push(`line ${lineOf(html, absolute)}: ${context(html, absolute)}`)
    }

    const declRe = /([a-z-]+)\s*:\s*([^;{}]+)/gi
    let d: RegExpExecArray | null
    while ((d = declRe.exec(body)) !== null) {
      const absolute = offset + d.index
      if (inRanges(absolute, ranges)) continue
      const value = (d[2] ?? '').toLowerCase()
      if (value.includes('var(')) continue
      for (const name of NAMED_COLOURS) {
        if (new RegExp(`(^|[\\s,(])${name}([\\s,)]|$)`).test(value)) {
          evidence.push(`line ${lineOf(html, absolute)}: ${d[1]}: ${(d[2] ?? '').trim()}`)
          break
        }
      }
    }
  }

  for (const st of s.styleAttrs) {
    if (/#[0-9a-fA-F]{3,8}|rgba?\(|hsla?\(/.test(st)) evidence.push(`inline style: ${st}`)
  }
  for (const attr of s.svgColourAttrs) {
    if (/#[0-9a-fA-F]{3,8}|rgba?\(|hsla?\(/.test(attr)) evidence.push(`svg attribute: ${attr}`)
  }

  return evidence.length === 0
    ? pass(id, label)
    : fail(
        id,
        label,
        `Found ${evidence.length} colour value(s) outside the :root block. Every colour is declared once in :root and referenced with var().`,
        evidence,
      )
}

function checkNoEmDash(html: string): CheckResult {
  const id = 'no_em_dash' as const
  const label = 'No em dashes'
  const evidence: string[] = []
  for (let i = 0; i < html.length; i++) {
    if (html.charCodeAt(i) === 0x2014) evidence.push(`line ${lineOf(html, i)}: ${context(html, i)}`)
  }
  return evidence.length === 0
    ? pass(id, label)
    : fail(id, label, `Found ${evidence.length} em dash character(s) (U+2014).`, evidence)
}

function checkNoEmoji(html: string): CheckResult {
  const id = 'no_emoji' as const
  const label = 'No emoji'
  // Extended_Pictographic covers emoji. Exclude the typographic symbols that share the property
  // and are legitimate on a business site: copyright, registered, trademark, info.
  const allowed = new Set([0x00a9, 0x00ae, 0x2122, 0x2139])
  const re = /\p{Extended_Pictographic}/gu
  const evidence: string[] = []
  let m: RegExpExecArray | null
  while ((m = re.exec(html)) !== null) {
    const cp = m[0].codePointAt(0)!
    if (allowed.has(cp)) continue
    evidence.push(`line ${lineOf(html, m.index)}: ${m[0]} in "${context(html, m.index, 50)}"`)
  }
  return evidence.length === 0
    ? pass(id, label)
    : fail(id, label, `Found ${evidence.length} emoji. Icons must be inline SVG.`, evidence)
}

function checkSingleH1(s: Structure): CheckResult {
  const id = 'single_h1' as const
  const label = 'Exactly one h1'
  const h1s = s.headings.filter((h) => h.level === 1)
  if (h1s.length === 1) return pass(id, label)
  return fail(
    id,
    label,
    `Found ${h1s.length} h1 elements. There must be exactly one, and it is the hero headline.`,
    h1s.map((h) => `h1: ${h.text}`),
  )
}

/**
 * Exactly one mobile sticky call bar.
 *
 * WHY THIS IS A CHECK AND NOT JUST A LINE IN THE PROMPT. The page is assembled from sections
 * generated by separate model calls. Two of them can each emit a bar without either being wrong
 * on its own, and the result renders as a duplicate: one copy sits high in the document, clipped
 * behind the fixed header, and the correct one sits after the footer. Nothing else in the suite
 * would notice, because both copies are valid markup on their own.
 *
 * ZERO IS ALSO A FAILURE. The bar is the call button on the device most of these customers are
 * found on, and a silently missing one is exactly the kind of absence that reads as a pass.
 */
function checkSingleMobileBar(s: Structure): CheckResult {
  const id = 'single_mobile_bar' as const
  const label = 'Exactly one mobile sticky bar'
  if (s.mobileBars.length === 1) return pass(id, label)
  if (s.mobileBars.length === 0) {
    return fail(
      id,
      label,
      'No element carries the mobile-bar class, so there is no fixed call bar on a phone.',
    )
  }
  return fail(
    id,
    label,
    `Found ${s.mobileBars.length} elements with the mobile-bar class. There must be exactly one, immediately after the footer. Remove every other copy, including any emitted inside or after the header.`,
    s.mobileBars.map((b) => `mobile-bar inside <${b.parent}>: class="${b.classes}"`),
  )
}

function checkHeadingHierarchy(s: Structure): CheckResult {
  const id = 'heading_hierarchy' as const
  const label = 'No skipped heading levels'
  const evidence: string[] = []
  let previous = 0
  for (const h of s.headings) {
    if (previous !== 0 && h.level > previous + 1) {
      evidence.push(`h${previous} is followed by h${h.level}: "${h.text}"`)
    }
    previous = h.level
  }
  return evidence.length === 0
    ? pass(id, label)
    : fail(id, label, 'Heading levels skip a step.', evidence)
}

function checkFooterCredit(s: Structure): CheckResult {
  const id = 'footer_credit' as const
  const label = 'Go Polar footer credit'
  const c = s.footerCredit
  if (!c) {
    return fail(
      id,
      label,
      `No link to ${FOOTER_CREDIT_HREF} found. The footer must contain: <a href="${FOOTER_CREDIT_HREF}" target="_blank" rel="noopener">${FOOTER_CREDIT_TEXT}</a>`,
    )
  }
  const problems: string[] = []
  if (c.text !== FOOTER_CREDIT_TEXT) {
    problems.push(`link text is "${c.text}", it must be exactly "${FOOTER_CREDIT_TEXT}"`)
  }
  if (c.target !== '_blank') problems.push(`target is "${c.target ?? 'missing'}", it must be _blank`)
  return problems.length === 0 ? pass(id, label) : fail(id, label, problems.join('; '), problems)
}

function checkJsonLd(s: Structure): CheckResult {
  const id = 'jsonld_valid' as const
  const label = 'JSON-LD parses'
  if (s.jsonLd.length === 0) {
    return fail(id, label, 'No JSON-LD block found. The @graph is required.')
  }
  const evidence: string[] = []
  for (const [i, block] of s.jsonLd.entries()) {
    try {
      JSON.parse(block)
    } catch (err) {
      evidence.push(`block ${i + 1}: ${(err as Error).message}`)
    }
  }
  return evidence.length === 0
    ? pass(id, label)
    : fail(id, label, 'A JSON-LD block does not parse as JSON.', evidence)
}

function checkFormAction(s: Structure): CheckResult {
  const id = 'form_action' as const
  const label = 'Forms post to Web3Forms'
  if (s.forms.length === 0) {
    return fail(id, label, 'No form found. The build needs a hero form and a contact form.')
  }
  const bad = s.forms.filter((f) => f.action !== FORM_ACTION)
  if (bad.length > 0) {
    return fail(
      id,
      label,
      `${bad.length} form(s) do not post to ${FORM_ACTION}.`,
      bad.map((f) => `action="${f.action ?? 'missing'}"`),
    )
  }
  if (s.forms.length < 2) {
    return fail(id, label, 'Only one form found. There must be a hero form and a contact form.')
  }
  return pass(id, label)
}

function checkImgAlt(s: Structure): CheckResult {
  const id = 'img_alt' as const
  const label = 'Every image has alt text'
  const bad = s.imgs.filter((i) => !i.alt || i.alt.trim().length === 0)
  return bad.length === 0
    ? pass(id, label)
    : fail(
        id,
        label,
        `${bad.length} image(s) have no alt text.`,
        bad.map((i) => `<img src="${i.src}">`),
      )
}

function checkLang(s: Structure): CheckResult {
  const id = 'lang_attr' as const
  const label = 'lang="en-AU"'
  return s.htmlLang === 'en-AU'
    ? pass(id, label)
    : fail(id, label, `<html lang> is "${s.htmlLang ?? 'missing'}", it must be "en-AU".`)
}

function checkFreeQuote(html: string, facts: BuildFacts): CheckResult {
  const id = 'free_quote_absent' as const
  const label = 'No "free quote" when free quotes is No'
  if (facts.freeQuotes) {
    return { id, label, status: 'skipped', detail: 'Business does offer free quotes.' }
  }
  const evidence: string[] = []
  const re = /free\s+quote/gi
  let m: RegExpExecArray | null
  while ((m = re.exec(html)) !== null) {
    evidence.push(`line ${lineOf(html, m.index)}: ${context(html, m.index)}`)
  }
  return evidence.length === 0
    ? pass(id, label)
    : fail(
        id,
        label,
        `This business does not offer free quotes, and "free quote" appears ${evidence.length} time(s). Use "request a quote" or "get a price".`,
        evidence,
      )
}

/**
 * No tag is showing itself to the reader.
 *
 * "&lt;em&gt;" in a document is a tag that was escaped rather than rendered, and the reader sees
 * the angle brackets. On these sites that is never deliberate: nothing here quotes HTML, so the
 * only way it appears is that model output containing markup reached a field the renderer escapes.
 *
 * Four pages shipped this way, on Driftwood Building Co and LSV Services, with a heading reading
 * "Timber decks built for <em>Bass Coast living</em>". Twenty checks passed on each, because the
 * document was perfectly valid HTML that happened to say something ridiculous. Validity was never
 * the question a reader asks.
 *
 * The plan schema now strips markup on the way in, which is the actual fix. This is the check
 * behind it, because a constraint enforced only where the data is written is one refactor away
 * from being enforced nowhere.
 */
function checkNoEscapedMarkup(html: string): CheckResult {
  const id = 'no_escaped_markup' as const
  const label = 'No escaped HTML tags visible in the copy'

  const evidence: string[] = []
  // A tag name, escaped. Deliberately narrow: "&lt;" on its own is fine, "a &lt; b" is prose.
  const re = /&lt;\/?[a-zA-Z][a-zA-Z0-9]*(?:\s[^&]*?)?\s*\/?&gt;/g
  let m: RegExpExecArray | null
  while ((m = re.exec(html)) !== null) {
    evidence.push(`line ${lineOf(html, m.index)}: ${context(html, m.index)}`)
    if (evidence.length >= 8) break
  }

  return evidence.length === 0
    ? pass(id, label)
    : fail(
        id,
        label,
        `${evidence.length} escaped HTML tag(s) are being shown to the reader as text. The copy that produced this contained markup in a field that is plain text.`,
        evidence,
      )
}

/**
 * The logo is drawn in the ratio it actually is.
 *
 * THIS EXISTS BECAUSE THE PROMPT ONCE COULD NOT BE OBEYED. The model is told to write width and
 * height on the logo, and for a long time it was handed the logo's PATH and nothing else, so it
 * guessed the shape. Driftwood Building Co's mark is 565 by 600, very nearly square; the model
 * wrote 150 by 40, the proportions of a typical wide wordmark, and the customer's own branding
 * rendered squashed to a quarter of its proper width in the header of the first page they open.
 *
 * Every other check passed on that page. Nothing in the set compared what the file IS against what
 * the document CLAIMS it is, so the one visibly broken thing on the site was the one thing not
 * being looked at. The dimensions are now in the prompt, but a prompt is a request and this is the
 * verification: the real size is known here, the declared size is readable here, and they have to
 * agree.
 *
 * Skipped when no logo was supplied, because there is then nothing to compare. A CSS wordmark has
 * no img and no intrinsic ratio to get wrong.
 */
function checkLogoAspect(html: string, facts: BuildFacts): CheckResult {
  const id = 'logo_aspect' as const
  const label = 'Logo drawn in its real aspect ratio'

  const logo = facts.logo
  if (!logo || !logo.width || !logo.height) {
    return { id, label, status: 'skipped', detail: 'No logo image supplied, so there is no ratio to honour.' }
  }

  const real = logo.width / logo.height
  const paths = [logo.path, logo.fallback].filter(Boolean) as string[]
  const names = paths.map((p) => p.split('/').pop()!)

  const evidence: string[] = []
  let found = 0

  for (const m of html.matchAll(/<img\b[^>]*>/gi)) {
    const tag = m[0]
    const src = /\bsrc\s*=\s*["']([^"']+)["']/i.exec(tag)?.[1] ?? ''
    if (!names.some((n) => src.endsWith(n))) continue
    found++

    const w = Number(/\bwidth\s*=\s*["']?(\d+)/i.exec(tag)?.[1] ?? '')
    const h = Number(/\bheight\s*=\s*["']?(\d+)/i.exec(tag)?.[1] ?? '')
    if (!w || !h) {
      evidence.push(`line ${lineOf(html, m.index)}: logo <img> is missing width or height.`)
      continue
    }

    const drawn = w / h
    // Ten percent. Rounding to whole pixels on a small logo moves the ratio a little, and that is
    // not what this is looking for; it is looking for a square drawn as a letterbox.
    if (Math.abs(drawn - real) / real > 0.1) {
      evidence.push(
        `line ${lineOf(html, m.index)}: drawn ${w}x${h} (ratio ${drawn.toFixed(2)}) but the file is ` +
          `${logo.width}x${logo.height} (ratio ${real.toFixed(2)}). ` +
          `At height ${h} the width must be about ${Math.round(h * real)}.`,
      )
    }
  }

  if (found === 0) {
    return {
      id,
      label,
      status: 'skipped',
      detail: `A logo was supplied at ${logo.path} but the page does not reference it, so the build is using a text or CSS treatment.`,
    }
  }

  return evidence.length === 0
    ? pass(id, label)
    : fail(
        id,
        label,
        `The logo is drawn in the wrong proportions, which stretches or squashes the customer's branding.`,
        evidence,
      )
}

/** Every relative path the document references. Shared by checks 12 and 17. */
export function referencedPaths(html: string, s: Structure): string[] {
  const referenced = new Set<string>()
  const add = (raw: string) => {
    const value = raw.trim().split(/\s+/)[0] ?? ''
    if (!value) return
    if (/^(https?:|data:|tel:|mailto:|#|\/\/)/i.test(value)) return
    referenced.add(value.replace(/^\.\//, ''))
  }

  for (const img of s.imgs) add(img.src)
  for (const srcset of s.sources) for (const part of srcset.split(',')) add(part)
  for (const href of s.linkHrefs) add(href)
  for (const src of s.scriptSrcs) add(src)
  for (const m of html.matchAll(/url\(\s*['"]?([^'")]+)['"]?\s*\)/gi)) add(m[1] ?? '')
  for (const m of html.matchAll(/srcset\s*=\s*"([^"]+)"/gi)) {
    for (const part of (m[1] ?? '').split(',')) add(part)
  }

  return [...referenced]
}

/**
 * Collapse a page-relative reference to a site-relative one.
 *
 * "../../assets/photo-01.webp" on a page at services/x/index.html is the same file as
 * "assets/photo-01.webp" at the root. Without this every image on every service page reads as
 * missing, which is how a correct page set fails its own check.
 */
function resolveAgainstPage(ref: string): string {
  return ref.replace(/^(?:\.\.\/)+/, '')
}

function checkAssets(html: string, s: Structure, facts: BuildFacts): CheckResult {
  const id = 'assets_exist' as const
  const label = 'Referenced assets exist'
  const allowed = new Set(Object.keys(facts.assetManifest))
  /*
   * favicon.svg is shipped, but not from the asset manifest.
   *
   * The manifest holds files uploaded by the customer and processed into variants. The favicon
   * is GENERATED at publish time from the brand colour and their initials, and written straight
   * into the published site beside index.html, so it never appears in the manifest and this
   * check would call every page broken. It is a real file at a real path either way.
   */
  allowed.add('favicon.svg')
  const missing = referencedPaths(html, s)
    .map(resolveAgainstPage)
    .filter((r) => !allowed.has(r))

  return missing.length === 0
    ? pass(id, label)
    : fail(
        id,
        label,
        `${missing.length} referenced file(s) do not exist. The only files that will ship are: ${[...allowed].join(', ') || 'none'}.`,
        missing,
      )
}

// ---------------------------------------------------------------------------------------------
// Check 17: page weight
// ---------------------------------------------------------------------------------------------

/**
 * What a first-time visitor actually downloads.
 *
 * This is a cost control as much as a speed one. These are static sites with plain image tags
 * served from Vercel, where bandwidth is billed, so page weight is a recurring bill for every
 * visit to every site, forever. See DECISIONS.md D25.
 */
export function checkPageWeight(html: string, s: Structure, facts: BuildFacts): CheckResult {
  const id = 'page_weight' as const
  const label = 'Page weight within budget'
  const total = pageWeight(html, referencedPaths(html, s), facts.assetManifest)

  const heaviest = Object.entries(facts.assetManifest)
    .filter(([path]) => !/\.jpe?g$/i.test(path))
    .sort((a, b) => b[1].bytes - a[1].bytes)
    .slice(0, 5)
    .map(([path, meta]) => `${path}: ${formatBytes(meta.bytes)}`)

  const summary = `${formatBytes(total)} total, HTML ${formatBytes(new TextEncoder().encode(html).byteLength)}`

  if (total > PAGE_WEIGHT_FAIL) {
    return fail(
      id,
      label,
      `${summary}. That is over the ${formatBytes(PAGE_WEIGHT_FAIL)} hard limit. Drop images or use the thumbnail variants in the gallery.`,
      heaviest,
    )
  }
  if (total > PAGE_WEIGHT_WARN) {
    return {
      id,
      label,
      status: 'warn',
      detail: `${summary}. Over the ${formatBytes(PAGE_WEIGHT_WARN)} warning line, target is ${formatBytes(PAGE_WEIGHT_TARGET)}.`,
      evidence: heaviest,
    }
  }
  return { id, label, status: 'pass', detail: summary }
}

/** Page weight on its own, for recording against the build. */
export function measurePageWeight(html: string, facts: BuildFacts): number {
  return pageWeight(html, referencedPaths(html, readStructure(html)), facts.assetManifest)
}

// ---------------------------------------------------------------------------------------------

/**
 * The FAQ copy on the page must match the FAQPage schema word for word (brief s5).
 * Folded into the JSON-LD check so the numbered list of checks stays the numbered list.
 */
function faqMismatchEvidence(html: string, s: Structure): string[] {
  const evidence: string[] = []

  // Compare against the visible copy only. Searching the whole document would find the FAQ text
  // inside the JSON-LD itself and every comparison would trivially pass, which is the bug this
  // check exists to catch.
  const pageText = html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')

  for (const block of s.jsonLd) {
    let parsed: unknown
    try {
      parsed = JSON.parse(block)
    } catch {
      continue
    }
    const graph = (parsed as { '@graph'?: unknown[] })['@graph'] ?? []
    for (const node of graph as Array<Record<string, unknown>>) {
      if (node['@type'] !== 'FAQPage') continue
      const questions = (node.mainEntity ?? []) as Array<Record<string, unknown>>
      for (const q of questions) {
        const name = String(q.name ?? '').replace(/\s+/g, ' ').trim()
        const answer = String((q.acceptedAnswer as Record<string, unknown> | undefined)?.text ?? '')
          .replace(/\s+/g, ' ')
          .trim()
        if (name && !pageText.includes(name)) {
          evidence.push(`FAQ question in schema but not in page copy: "${name}"`)
        }
        if (answer && !pageText.includes(answer)) {
          evidence.push(`FAQ answer in schema does not match page copy: "${answer.slice(0, 80)}"`)
        }
      }
    }
  }
  return evidence
}

/**
 * A page somebody paid twenty five dollars for has its own middle, not just its own heading.
 *
 * THE MEASUREMENT THAT PUT THIS HERE. Two service pages off a real build, compared block by
 * block: 480 words of visible text, 350 of them IDENTICAL on both pages, 130 about the actual
 * service. The renderer was reprinting the home page process steps and the home page FAQ on
 * every service page, so the two largest sections of a page about decking were about the
 * business in general. Nothing noticed, because every page was valid, complete and passed.
 *
 * The plan schema now carries steps, scopeFactors and faqs per page, and the house rules ask
 * for them. A prompt instruction is a hope, so this is the part that looks. The renderer
 * stamps where each section came from, because a filled page and a fallback page are the same
 * markup apart from the words.
 *
 * WARN, NOT FAIL, AND THE REASON IS NOT SQUEAMISHNESS. Repair is off for template output, so
 * a fail holds the job. The one case that legitimately has no steps is the page
 * enforcePlanInvariants synthesises when the model omitted a page the customer paid for:
 * synthesised copy cannot know how a retaining wall gets built, and it is deliberately plain
 * because thin and true beats padded and wrong. Failing here would block exactly the case the
 * fallback exists to rescue, and would turn a thin page into no website at all.
 */
export function checkServicePageSubstance(html: string): CheckResult {
  const label = 'Service pages are about their own service'
  const canonical = /<link[^>]+rel="canonical"[^>]+href="([^"]*)"/i.exec(html)?.[1] ?? ''
  if (!canonical.includes('/services/')) {
    return { id: 'service_page_substance', label, status: 'pass', detail: 'Not a service page.' }
  }

  const wanted: [string, string][] = [
    ['service_process', 'steps: how this job actually runs'],
    ['service_scope', 'scopeFactors: what makes this job bigger or smaller'],
    ['service_faq', 'faqs: questions about this service'],
  ]
  const missing = wanted.filter(([m]) => !html.includes('data-gp="' + m + '"'))

  if (missing.length === 0) {
    return {
      id: 'service_page_substance',
      label,
      status: 'pass',
      detail: 'Its own steps, scope factors and questions.',
    }
  }

  return {
    id: 'service_page_substance',
    label,
    status: 'warn',
    detail:
      missing.length +
      ' of 3 page-specific sections are missing, so this page uses the home page content ' +
      'in their place. The customer paid for this page.',
    evidence: missing.map(([, why]) => why),
  }
}

/**
 * Every colour this template puts on top of another one, checked without a browser.
 *
 * WHY THIS EXISTS SEPARATELY FROM CHECK 25. Check 25 measures what a browser actually painted,
 * which is the truth, and it is a RENDER check: production runs with RENDER_DRIVER=none because
 * there is no browser in the function, so on a real customer build it reports skipped. Every
 * invisible-text bug this project has shipped was therefore caught by me running Chrome by
 * hand, or by the customer.
 *
 * This one needs no browser. The renderer writes every colour into :root as a token, and every
 * component takes its foreground and background from that same set, so the pairs are knowable
 * from the document itself. It reads the :root the page actually shipped with, resolves the
 * var() chains, and does the arithmetic. That makes it a STATIC check, which runs everywhere.
 *
 * IT IS PALETTE-DEPENDENT, WHICH IS THE WHOLE POINT. White suburb pills on a light tint passed
 * every test on the fixture and shipped on a customer whose tint was pale. The pairs below are
 * fixed; the colours in them come from the customer.
 *
 * The threshold is 1.5, matching check 25 and for the same reason: this is an invisibility
 * alarm, not an accessibility grade. AA is 4.5 and would fail muted body copy that is legible
 * and chosen on purpose. White on white is 1.0.
 */
const COLOUR_PAIRS: [fg: string, bg: string, where: string][] = [
  ['--page-fg', '--page-bg', 'body text on the page background'],
  ['--card-fg', '--card-bg', 'text on cards'],
  ['--card-fg', '--alt-bg', 'suburb pills and tinted panels'],
  ['--on-dark', '--dark-block', 'text on the dark bands'],
  ['--eyebrow-color', '--page-bg', 'section labels on the light sections'],
  ['--eyebrow-on-dark', '--dark-block', 'section labels on the dark bands'],
  ['--on-btn', '--btn-bg', 'the label on a filled button'],
]

/** The :root block as a map, with var() chains followed to a real colour. */
export function rootTokens(html: string): Record<string, string> {
  const block = /:root\{([^}]*)\}/.exec(html)?.[1] ?? ''
  const raw: Record<string, string> = {}
  for (const decl of block.split(';')) {
    const at = decl.indexOf(':')
    if (at <= 0) continue
    const name = decl.slice(0, at).trim()
    if (name.startsWith('--')) raw[name] = decl.slice(at + 1).trim()
  }
  const resolve = (value: string, depth = 0): string => {
    if (depth > 6) return value
    const m = /^var\((--[a-z0-9-]+)\)$/i.exec(value.trim())
    if (!m) return value.trim()
    const next = raw[m[1]!]
    return next === undefined ? value.trim() : resolve(next, depth + 1)
  }
  const out: Record<string, string> = {}
  for (const key of Object.keys(raw)) out[key] = resolve(raw[key]!)
  return out
}

function luminance(hex: string): number | null {
  const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(hex.trim())
  if (!m) return null
  let h = m[1]!
  if (h.length === 3) h = h.split('').map((c) => c + c).join('')
  const parts = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
  const f = parts.map((v) => (v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4)))
  return 0.2126 * f[0]! + 0.7152 * f[1]! + 0.0722 * f[2]!
}

export function checkColourPairs(html: string): CheckResult {
  const label = 'No text is the colour of what it sits on'
  const tokens = rootTokens(html)
  const bad: string[] = []

  for (const [fgName, bgName, where] of COLOUR_PAIRS) {
    const fg = tokens[fgName]
    const bg = tokens[bgName]
    if (!fg || !bg) continue
    const a = luminance(fg)
    const b = luminance(bg)
    // Anything that is not a plain hex (a gradient, a colour function) is not judged here.
    if (a === null || b === null) continue
    const ratio = (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05)
    if (ratio < 1.5) {
      bad.push(
        where + ': ' + fgName + ' (' + fg + ') on ' + bgName + ' (' + bg + ') is ' +
          ratio.toFixed(2) + ':1',
      )
    }
  }

  if (bad.length === 0) {
    return { id: 'colour_pairs_readable', label, status: 'pass' }
  }
  return {
    id: 'colour_pairs_readable',
    label,
    status: 'fail',
    detail:
      bad.length +
      ' colour pairing(s) are close to invisible: the text and the thing behind it are within ' +
      'a contrast ratio of 1.5, where identical is 1.0. Change one of the two colours named ' +
      'below. A colour that works on the dark bands is often wrong on the light sections, so ' +
      'check both: sectionCopy[section].eyebrowColor sets one section without moving the rest.',
    evidence: bad,
  }
}

export async function runStaticChecks(html: string, facts: BuildFacts): Promise<CheckResult[]> {
  const s = readStructure(html)

  const results: CheckResult[] = [
    checkHexOutsideRoot(html, s),
    checkNoEmDash(html),
    checkNoEmoji(html),
    checkSingleH1(s),
    checkSingleMobileBar(s),
    checkHeadingHierarchy(s),
    checkFooterCredit(s),
    checkJsonLd(s),
    checkFormAction(s),
    checkImgAlt(s),
    checkLang(s),
    checkFreeQuote(html, facts),
    checkLogoAspect(html, facts),
    checkNoEscapedMarkup(html),
    checkAssets(html, s, facts),
    checkPageWeight(html, s, facts),
    checkServicePageSubstance(html),
    checkColourPairs(html),
  ]

  const jsonLd = results.find((r) => r.id === 'jsonld_valid')!
  if (jsonLd.status === 'pass') {
    const mismatches = faqMismatchEvidence(html, s)
    if (mismatches.length > 0) {
      jsonLd.status = 'fail'
      jsonLd.detail =
        'JSON-LD parses, but the FAQ copy on the page does not match the FAQPage schema word for word.'
      jsonLd.evidence = mismatches.slice(0, 8)
    }
  }

  return results
}
