/**
 * Every product, price and Shopify identifier in the business, in one place.
 *
 * PRICES ARE GST-INCLUSIVE, because the store is. `taxesIncluded: true`, verified on
 * itscold.com.au. The app displays the number the customer is actually charged, labelled
 * "inc GST", because advertising "$30 + GST" and then landing a tradie on a $33.00 checkout reads
 * as a bait and switch. One number, the real one, everywhere. See DECISIONS.md D31.
 *
 * HOW A PRODUCT IS IDENTIFIED, and why it is not always the handle.
 *
 * The three subscription products are identified by their Shopify **handle**, which is known and
 * stable. The three one-off products created on 2026-08-19 are identified by their **SKU**, which
 * was set deliberately to a known value, while their handles were auto-generated by Shopify from
 * titles nobody here chose ("DIY Website Build" and so on). Guessing a handle from a title is
 * exactly the sort of assumption that produces a checkout link that 404s, so this file records
 * which kind of identifier each product actually has and uses that. See DECISIONS.md D35.
 *
 * THE RULES THAT REMAIN NON-NEGOTIABLE.
 *
 * 1. NO INVENTED IDENTIFIERS. A product that does not exist has `ref: null`, and a checkout for it
 *    throws by name saying what to create.
 * 2. NO INVENTED PRICES. `extra-edits` has never been priced, so nothing shows a number for it.
 * 3. SELLING PLANS ARE NOT OPTIONAL. All three subscriptions have `requiresSellingPlan: true`, so
 *    Shopify REJECTS a line without a plan id. A missing plan id is fatal, not a downgrade.
 * 4. THE STORE IS THE AUTHORITY ON WHETHER SOMETHING CAN BE SOLD. All six products are published
 *    and active as of 2026-08-19, but this file is not what decides that: `checkStoreProducts` in
 *    server/lib/shopify.ts asks Shopify immediately before every checkout, so a product being
 *    unpublished, archived or re-priced is caught without anybody having to remember to edit here.
 */

export type PriceKey =
  | 'build'
  | 'additionalPage'
  | 'hosting'
  | 'domain'
  | 'email'
  | 'postLiveEdit'
  | 'extraEdits'
  | 'discharge'

export type OrderKind = 'build' | 'page' | 'hosting' | 'domain' | 'email' | 'edit' | 'discharge'

/** Australian GST. Used only to convert between the two ways of stating the same price. */
export const GST_RATE = 0.1

export interface Product {
  /**
   * The stable identifier this app sells by. NULL MEANS THE PRODUCT DOES NOT EXIST on the store,
   * and nothing may treat that as licence to guess one.
   */
  ref: string | null
  /** Which kind of Shopify identifier `ref` is. Handles and SKUs are not interchangeable. */
  refKind: 'handle' | 'sku'
  /** What `ref` will be once the product is created. Documentation for SHOPIFY-SETUP.md. */
  proposedRef: string
  label: string
  /** What the customer is charged, GST included, in whole cents. null means no price may be shown. */
  incGstCents: number | null
  recurrence: 'once' | 'monthly'
  kind: OrderKind
  /** True where the store sets requiresSellingPlan. Such a line is refused without a plan id. */
  requiresSellingPlan: boolean
  /** Verified numeric variant id, where it is known. An env var of the same name overrides it. */
  variantId: string | null
  /** Verified numeric product id. How SKU-identified products are looked up on the store. */
  productId: string | null
  /**
   * The product's real Shopify handle, for reference only.
   *
   * NOTHING SELLS BY THIS for a SKU-identified product. It is recorded because it is now known and
   * because somebody looking at a Shopify URL should be able to find the product here, but the app
   * matches on variant id and SKU. A handle changes when somebody edits a title; a SKU does not.
   */
  storeHandle: string | null
  store: StoreState
}

export interface StoreState {
  exists: boolean
  title?: string
  /**
   * Created but not published. A draft product cannot be bought by anybody, so this blocks the
   * same way a missing product does. Nothing sets it today: all six are published. Kept because
   * the next product created will start life in draft too.
   */
  draft?: boolean
  sellingPlan?: { group: string; plan: string; interval: 'MONTH' | 'YEAR'; intervalCount: number }
  /** What is left to do, in Chris's terms. Rendered into SHOPIFY-SETUP.md. */
  todo?: string
  /** What breaks in this app until it is done. */
  breaks?: string
}

/** The store, verified on 2026-08-19. */
export const STORE = {
  name: 'Go Polar Creative',
  domain: 'itscold.com.au',
  plan: 'Basic',
  currency: 'AUD',
  timezone: 'AWST',
  /** Prices are entered with GST inside them. Everything about display follows from this. */
  taxesIncluded: true,
  subscriptionApp: 'Appstle',
  verifiedOn: '2026-08-19',
} as const

export const PRICING: Record<PriceKey, Product> = {
  build: {
    // Created and published 2026-08-19 as "DIY Website Build", handle diy-website-build. The app
    // sells by the SKU, because that is the identifier that was set deliberately: a handle follows
    // whatever the title happens to be.
    ref: 'build-token',
    refKind: 'sku',
    proposedRef: 'build-token',
    label: 'Website build',
    incGstCents: 22_000, // $220.00 = $200 + GST
    recurrence: 'once',
    kind: 'build',
    requiresSellingPlan: false,
    variantId: '62852208328863',
    productId: '10930413568159',
    storeHandle: 'diy-website-build',
    store: {
      exists: true,
      title: 'DIY Website Build',
      todo: 'Nothing. Published and verified active on 2026-08-19.',
    },
  },
  additionalPage: {
    // Created and published 2026-08-20. The build token buys one page; each of these buys another.
    // Bought at the original checkout or later through a generated link, and the webhook honours
    // line item quantity, so four in one go grants four. See DECISIONS.md D42.
    ref: 'additional-page',
    refKind: 'sku',
    proposedRef: 'additional-page',
    label: 'Additional page',
    incGstCents: 2_500, // $25.00
    recurrence: 'once',
    kind: 'page',
    requiresSellingPlan: false,
    variantId: '62852241948831',
    productId: '10930420875423',
    storeHandle: 'additional-diy-page',
    store: {
      exists: true,
      title: 'Additional DIY Page',
      todo: 'Nothing. Published and verified active on 2026-08-20.',
    },
  },
  hosting: {
    ref: 'website-hosting-australia',
    refKind: 'handle',
    proposedRef: 'website-hosting-australia',
    label: 'Hosting',
    incGstCents: 3_300, // $33.00 = $30 + GST
    recurrence: 'monthly',
    kind: 'hosting',
    requiresSellingPlan: true,
    variantId: null,
    productId: null,
    storeHandle: 'website-hosting-australia',
    store: {
      exists: true,
      title: 'Website Hosting',
      sellingPlan: { group: 'Website Hosting', plan: 'Monthly Subscription', interval: 'MONTH', intervalCount: 1 },
      todo: 'Nothing. Price and billing interval both correct.',
      breaks:
        'A second variant, "Hosting + 2 Monthly Website Edits" at $100.00, exists on the store and is not offered anywhere in this app. No decision on file.',
    },
  },
  domain: {
    ref: 'domain-1-year',
    refKind: 'handle',
    proposedRef: 'domain-1-year',
    label: 'Domain name',
    incGstCents: 550, // $5.50 = $5 + GST
    recurrence: 'monthly',
    kind: 'domain',
    requiresSellingPlan: true,
    variantId: null,
    productId: null,
    storeHandle: 'domain-1-year',
    store: {
      exists: true,
      title: 'Domain Hosting',
      sellingPlan: { group: 'Domain Hosting', plan: 'Monthly Subscription', interval: 'MONTH', intervalCount: 1 },
      todo: 'Nothing. The plan was billing YEAR and now bills MONTH.',
    },
  },
  email: {
    ref: 'email-hosting',
    refKind: 'handle',
    proposedRef: 'email-hosting',
    label: 'Custom email address',
    // DECIDED 2026-08-19: $14.95 including GST, which is $13.59 ex GST. Chosen on shelf price
    // rather than margin, because that is the number the market compares. The store is already
    // correct at $14.95 and needs no change. See DECISIONS.md D34.
    incGstCents: 1_495,
    recurrence: 'monthly',
    kind: 'email',
    requiresSellingPlan: true,
    variantId: null,
    productId: null,
    storeHandle: 'email-hosting',
    store: {
      exists: true,
      title: 'Email Hosting',
      sellingPlan: { group: 'Email Hosting', plan: 'Monthly Subscription', interval: 'MONTH', intervalCount: 1 },
      todo: 'Nothing. Price confirmed correct as it stands.',
    },
  },
  postLiveEdit: {
    ref: 'post-live-edit',
    refKind: 'sku',
    proposedRef: 'post-live-edit',
    label: 'Website update after launch',
    incGstCents: 11_000, // $110.00 = $100 + GST
    recurrence: 'once',
    kind: 'edit',
    requiresSellingPlan: false,
    variantId: '62852208361631',
    productId: '10930413600927',
    storeHandle: 'website-update',
    store: {
      exists: true,
      title: 'Website Update',
      todo: 'Nothing. Published and verified active on 2026-08-19.',
    },
  },
  extraEdits: {
    ref: null,
    refKind: 'sku',
    proposedRef: 'extra-edits',
    label: 'Another 5 edits before launch',
    // TODO(chris): still never decided. While this is null the UI shows no price and no buy button
    // and offers to put the customer in touch instead. Set the number and the path turns on.
    incGstCents: null,
    recurrence: 'once',
    kind: 'edit',
    requiresSellingPlan: false,
    variantId: null,
    productId: null,
    storeHandle: null,
    store: {
      exists: false,
      todo: 'Do not create it yet. Decide the price first.',
      breaks:
        'Nothing today. The price is undecided so the path is already dark by design: a customer out of edits is offered a conversation or going live, never a number.',
    },
  },
  discharge: {
    ref: 'discharge',
    refKind: 'sku',
    proposedRef: 'discharge',
    label: 'Discharge and file handover',
    incGstCents: 33_000, // $330.00 = $300 + GST
    recurrence: 'once',
    kind: 'discharge',
    requiresSellingPlan: false,
    variantId: '62852208394399',
    productId: '10930413633695',
    storeHandle: 'website-discharge',
    store: {
      exists: true,
      title: 'Website Discharge',
      todo: 'Nothing. Published and verified active on 2026-08-19.',
    },
  },
}

export const EDITS_INCLUDED = 10
export const EXTRA_EDITS_QUANTITY = 5

/** Whether a price is settled well enough to put in front of a customer. */
export function isPriceSet(key: PriceKey): boolean {
  return PRICING[key].incGstCents !== null
}

/** Ex-GST cents, for the order records. Never displayed. */
export function exGstCents(key: PriceKey): number | null {
  const inc = PRICING[key].incGstCents
  return inc === null ? null : Math.round(inc / (1 + GST_RATE))
}

/**
 * The only way to render a price, and it always says "inc GST" because on this store that is what
 * the number is. Returns null when the price is unresolved, and every caller degrades.
 */
export function formatPrice(key: PriceKey): string | null {
  const item = PRICING[key]
  if (item.incGstCents === null) return null

  const dollars = item.incGstCents / 100
  const amount = Number.isInteger(dollars) ? `$${dollars}` : `$${dollars.toFixed(2)}`
  const suffix = item.recurrence === 'monthly' ? '/month' : ''
  return `${amount}${suffix} inc GST`
}

// -----------------------------------------------------------------------------------------------
// Identifiers
// -----------------------------------------------------------------------------------------------

export class ProductNotOnStoreError extends Error {
  constructor(
    readonly key: PriceKey,
    readonly proposedRef: string,
  ) {
    const product = PRICING[key]
    super(
      `"${product.label}" does not exist on the Shopify store, so no checkout can be built for it. Create it with the SKU "${proposedRef}". ${
        product.store.todo ?? ''
      } Then set ${variantEnvKey(proposedRef)}. See SHOPIFY-SETUP.md. Until then: ${
        product.store.breaks ?? 'this path cannot complete.'
      }`,
    )
    this.name = 'ProductNotOnStoreError'
  }
}

export class PriceUnresolvedError extends Error {
  constructor(readonly key: PriceKey) {
    const product = PRICING[key]
    super(
      `"${product.label}" has no settled price, so it cannot be sold and no number may be shown. See SHOPIFY-SETUP.md.`,
    )
    this.name = 'PriceUnresolvedError'
  }
}

/**
 * The identifier to sell by, or a loud refusal. The only way a product reference reaches a
 * checkout, so neither a missing product nor an unsettled price can quietly become a broken cart.
 *
 * Being in draft is NOT checked here: the store is the authority on that and it is checked live
 * against the Admin API, so publishing a product takes effect immediately without a code change.
 */
export function checkoutRef(key: PriceKey): string {
  const product = PRICING[key]
  if (!product.ref) throw new ProductNotOnStoreError(key, product.proposedRef)
  if (product.incGstCents === null) throw new PriceUnresolvedError(key)
  return product.ref
}

export function kindForRef(ref: string): OrderKind | null {
  for (const product of Object.values(PRICING)) {
    if (product.ref === ref) return product.kind
    // A proposed ref matches too: if a product is created before this file is updated, an order
    // for it should still be understood rather than dropped on the floor.
    if (product.proposedRef === ref) return product.kind
  }
  return null
}

export function productForRef(ref: string): { key: PriceKey; product: Product } | null {
  for (const [key, product] of Object.entries(PRICING) as Array<[PriceKey, Product]>) {
    if (product.ref === ref || product.proposedRef === ref) return { key, product }
  }
  return null
}

export function knownRefs(): string[] {
  return Object.values(PRICING).flatMap((p) => (p.ref ? [p.ref, p.proposedRef] : [p.proposedRef]))
}

/**
 * Shopify variant and selling-plan ids, one env var per product, named from its ref:
 *
 *   SHOPIFY_VARIANT_BUILD_TOKEN=62852208328863
 *   SHOPIFY_SELLING_PLAN_WEBSITE_HOSTING_AUSTRALIA=6890123456
 *
 * Where a verified variant id is already recorded above, the env var is an override rather than a
 * requirement, so a different store can be pointed at without a code change.
 */
export function variantEnvKey(ref: string): string {
  return `SHOPIFY_VARIANT_${ref.replace(/-/g, '_').toUpperCase()}`
}

export function sellingPlanEnvKey(ref: string): string {
  return `SHOPIFY_SELLING_PLAN_${ref.replace(/-/g, '_').toUpperCase()}`
}

/** Env var first, then the id verified from the store. Null when neither is known. */
export function variantIdFor(ref: string, env: Record<string, string | undefined>): string | null {
  const fromEnv = env[variantEnvKey(ref)]?.trim()
  if (fromEnv) return fromEnv
  return productForRef(ref)?.product.variantId ?? null
}

// -----------------------------------------------------------------------------------------------
// Configuration report
// -----------------------------------------------------------------------------------------------

export interface ProductConfigProblem {
  key: PriceKey
  label: string
  /** The env var, the Shopify object, or the decision that is missing. */
  missing: string
  detail: string
  breaks: string
  /** True where this is a question for Chris rather than a value to paste in. */
  needsDecision?: boolean
  /** True where Chris has to do something in Shopify rather than here. */
  needsShopify?: boolean
}

/**
 * What is not configured yet, and what each gap costs.
 *
 * `env` is passed in so this stays pure and the client bundle never touches process.env.
 */
export function productConfigProblems(env: Record<string, string | undefined>): ProductConfigProblem[] {
  const problems: ProductConfigProblem[] = []

  for (const [key, product] of Object.entries(PRICING) as Array<[PriceKey, Product]>) {
    if (product.incGstCents === null) {
      problems.push({
        key,
        label: product.label,
        missing: `a decision on the price of "${product.label}"`,
        detail: 'The price has never been decided.',
        breaks: product.store.breaks ?? 'It cannot be sold.',
        needsDecision: true,
      })
    }

    if (!product.ref) {
      problems.push({
        key,
        label: product.label,
        missing: `Shopify product with SKU "${product.proposedRef}"`,
        detail: product.store.todo ?? 'Does not exist on the store.',
        breaks: product.store.breaks ?? 'This path cannot complete.',
        needsShopify: true,
      })
      continue
    }

    if (product.store.draft) {
      problems.push({
        key,
        label: product.label,
        missing: `"${product.store.title ?? product.label}" is still a draft on the store`,
        detail: 'It exists and is priced correctly, but a draft product cannot be bought by anybody.',
        breaks: product.store.breaks ?? 'It cannot be bought until it is published.',
        needsShopify: true,
      })
    }

    if (!variantIdFor(product.ref, env)) {
      problems.push({
        key,
        label: product.label,
        missing: variantEnvKey(product.ref),
        detail: 'No variant id is known for this product, from the environment or from the store.',
        breaks: 'Any checkout including this line fails with a configuration error.',
      })
    }

    if (product.requiresSellingPlan) {
      const planKey = sellingPlanEnvKey(product.ref)
      if (!env[planKey]?.trim()) {
        problems.push({
          key,
          label: product.label,
          missing: planKey,
          detail: `This product has requiresSellingPlan set on the store, so Shopify rejects any line without a selling plan id. Its plan is "${
            product.store.sellingPlan?.plan ?? 'Monthly Subscription'
          }" in the "${product.store.sellingPlan?.group ?? product.label}" group.`,
          breaks: 'The checkout is rejected outright. Not a downgrade to a one-off charge, a refusal.',
        })
      }
    }
  }

  return problems
}
