// Trade list, per-trade service presets, and the schema.org LocalBusiness subtype map.
// Shared by the intake wizard (chips) and the Worker (JSON-LD generation).

export const TRADES = [
  'plumber',
  'electrician',
  'roofer',
  'hvac',
  'builder',
  'landscaper',
  'excavation',
  'concreter',
  'painter',
  'tiler',
  'fencing',
  'pest',
  'other',
] as const

export type Trade = (typeof TRADES)[number]

export const TRADE_LABELS: Record<Trade, string> = {
  plumber: 'Plumber',
  electrician: 'Electrician',
  roofer: 'Roofer',
  hvac: 'HVAC / air conditioning',
  builder: 'Builder',
  landscaper: 'Landscaper',
  excavation: 'Excavation',
  concreter: 'Concreter',
  painter: 'Painter',
  tiler: 'Tiler',
  fencing: 'Fencing',
  pest: 'Pest control',
  other: 'Other',
}

// schema.org LocalBusiness subtype per trade (brief s5, SEO baseline).
// schema.org only defines a handful of trade subtypes under HomeAndConstructionBusiness:
// Electrician, GeneralContractor, HVACBusiness, HousePainter, Locksmith, MovingCompany,
// Plumber, RoofingContractor. Anything without a dedicated type falls back to the nearest
// valid parent rather than an invented type, because an invented @type is ignored by Google.
export const TRADE_SCHEMA_TYPE: Record<Trade, string> = {
  plumber: 'Plumber',
  electrician: 'Electrician',
  roofer: 'RoofingContractor',
  hvac: 'HVACBusiness',
  builder: 'GeneralContractor',
  landscaper: 'HomeAndConstructionBusiness',
  excavation: 'GeneralContractor',
  concreter: 'GeneralContractor',
  painter: 'HousePainter',
  tiler: 'HomeAndConstructionBusiness',
  fencing: 'HomeAndConstructionBusiness',
  // ASSUMPTION: schema.org has no PestControlService type. LocalBusiness is the honest parent.
  pest: 'LocalBusiness',
  other: 'LocalBusiness',
}

// Preset service chips. The customer picks 3-8 and can add custom ones.
// These come from the language used in the 59 real submissions, not from a keyword tool.
export const SERVICE_PRESETS: Record<Trade, string[]> = {
  plumber: [
    'Blocked drains',
    'Hot water systems',
    'Burst pipes',
    'Leak detection',
    'Tap and toilet repairs',
    'Bathroom renovations',
    'Gas fitting',
    'Roof plumbing',
    'Backflow prevention',
    'CCTV drain camera',
  ],
  electrician: [
    'Switchboard upgrades',
    'Power points and lighting',
    'Ceiling fans',
    'Safety switch installation',
    'Fault finding',
    'Rewiring',
    'EV charger installation',
    'Smoke alarms',
    'Data and TV points',
    'Solar and battery',
  ],
  roofer: [
    'Roof restoration',
    'Roof repairs',
    'Re-roofing',
    'Metal roofing',
    'Tile roofing',
    'Gutter replacement',
    'Leak repairs',
    'Roof painting',
    'Skylight installation',
  ],
  hvac: [
    'Split system installation',
    'Ducted air conditioning',
    'Air conditioning repairs',
    'Servicing and maintenance',
    'Evaporative cooling',
    'Ventilation',
    'Commercial HVAC',
    'Heating installation',
  ],
  builder: [
    'Home extensions',
    'Renovations',
    'New home builds',
    'Decks and pergolas',
    'Bathroom renovations',
    'Kitchen renovations',
    'Carports and garages',
    'Structural repairs',
  ],
  landscaper: [
    'Garden design',
    'Turf laying',
    'Retaining walls',
    'Irrigation systems',
    'Paving',
    'Garden maintenance',
    'Tree and hedge work',
    'Decking',
    'Fencing',
  ],
  excavation: [
    'Site preparation',
    'Bulk earthworks',
    'Trenching',
    'Pool excavation',
    'Driveway preparation',
    'Demolition',
    'Rock breaking',
    'Drainage',
  ],
  concreter: [
    'Driveways',
    'Concrete slabs',
    'Exposed aggregate',
    'Concrete paths',
    'Patios and alfresco',
    'Shed slabs',
    'Decorative concrete',
    'Concrete repairs',
  ],
  painter: [
    'Interior painting',
    'Exterior painting',
    'Roof painting',
    'Commercial painting',
    'Rendering',
    'Wallpaper removal',
    'Timber staining',
    'Repaints and touch ups',
  ],
  tiler: [
    'Bathroom tiling',
    'Kitchen splashbacks',
    'Floor tiling',
    'Waterproofing',
    'Outdoor tiling',
    'Pool tiling',
    'Tile repairs',
    'Screeding',
  ],
  fencing: [
    'Colorbond fencing',
    'Timber fencing',
    'Pool fencing',
    'Gates and automation',
    'Retaining walls',
    'Rural fencing',
    'Fence repairs',
    'Privacy screens',
  ],
  pest: [
    'Termite inspections',
    'Termite treatment',
    'General pest control',
    'Cockroach treatment',
    'Ant control',
    'Spider spraying',
    'Rodent control',
    'Pre-purchase inspections',
  ],
  other: [],
}
