import { getDb } from './client'
import { config } from '../config'

/**
 * Apply migrations generated by drizzle-kit.
 *
 * The same SQL runs against Neon in production and against the embedded PGlite database locally,
 * because both are Postgres. Local development therefore needs no database server, no container
 * and no account, which is what makes a fresh clone runnable (DECISIONS.md D22).
 */
export async function migrate(): Promise<void> {
  const cfg = config()
  const db = await getDb()
  const folder = 'db/migrations'

  if (cfg.databaseDriver === 'pglite') {
    const { migrate: run } = await import('drizzle-orm/pglite/migrator')
    await run(db as never, { migrationsFolder: folder })
    return
  }

  const { migrate: run } = await import('drizzle-orm/postgres-js/migrator')
  await run(db as never, { migrationsFolder: folder })
}
